Add Microsoft Teams support
smartprix/notify pull request #3
Opened 2019-07-18 13:40 UTC by ajeet-smpx

closes #1

2019-07-18 14:17 UTC, rohit-gohri requested changes
Also make dummy functions for username and icon that return this and do nothing

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +function getPackageInfo() {
could import this from index

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +function getLogger() {
same for this

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +function getPackageInfo() {
or create a helpers file

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +	constructor({text = '', channel = ''} = {}) {
can remove default values

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +	summary(summary) {
Add summary in Slack class too, which sets the fallback in the first attachement

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +	section(sections) {
this could be renamed to attachment

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +	action(actions) {
Is this equivalent to button?

2019-07-18 14:17 UTC, rohit-smpx commented on teams.js
> +	errorSection(err, {label = '', title = ''} = {}) {
Could make this static or remove,  no need to for two fns to do similar things

2019-07-18 14:18 UTC, ajeet-smpx commented on teams.js
> +function getPackageInfo() {
:+1:

2019-07-18 14:40 UTC, ajeet-smpx commented on teams.js
> +	action(actions) {
No

2019-07-19 06:16 UTC, ajeet-smpx commented on teams.js
> +	constructor({text = '', channel = ''} = {}) {
typescript error

2019-07-19 06:23 UTC, rohit-smpx commented on teams.js
> +	constructor({text = '', channel = ''} = {}) {
Make them optional through jsdoc

2019-07-19 06:24 UTC, rohit-smpx commented on index.d.ts
>  	};
Add export for Slack here too

2019-07-19 06:39 UTC, rohit-smpx commented on slack.js
> +		return 'slackbot';
Add setter for this too

2019-07-19 06:40 UTC, rohit-smpx commented on teams.js
> +	username() { return this }
add comment that Teams doesn't support these options

2019-07-22 06:35 UTC, rohit-gohri approved these changes

2019-07-23 09:22 UTC, merged